package constants

var ENV = []string{
	"SERVER_PORT",
	"MIGRATE",
	"POSTGRES_USER",
	"POSTGRES_PASS",
	"POSTGRES_DB",
	"POSTGRES_HOST",
	"POSTGRES_PORT",
	"REDIS_HOST",
	"REDIS_PORT",
	"SMTP_SERVER",
	"SMTP_PASSWORD",
	"SMTP_PORT",
	"SMTP_USER",
}
